import { CheckCircle2, CircleAlert, Clock3, Database, Gauge, Globe2, Moon, Server, Sun, WifiOff } from 'lucide-react';
import { useGetOperationsSummary, useListProviderHealth } from '@workspace/api-client-react';
import { usePreferences } from '@/components/platform-shell';
import { getTranslations } from '@/lib/i18n';

export default function MorePage() {
  const { language, setLanguage, dark, setDark } = usePreferences();
  const providers = useListProviderHealth();
  const summary = useGetOperationsSummary();
  const labels = getTranslations(language).more;
  const statusLabels = getTranslations(language).status;

  return <div className="space-y-8">
    <section className="rise-in"><p className="mono-font text-[10px] font-bold uppercase tracking-[0.24em] text-primary">{labels.eyebrow}</p><h1 className="display-font mt-3 text-4xl font-bold tracking-[-0.05em] sm:text-5xl">{labels.title}</h1><p className="mt-2 text-sm text-muted-foreground">{labels.subtitle}</p></section>
    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
      <div className="rounded-2xl border border-card-border bg-card p-5 sm:p-6">
        <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Server className="size-5" /></div><div><h2 className="font-bold">{labels.operations}</h2><p className="text-xs text-muted-foreground">{labels.summary}</p></div></div><span className="mono-font rounded-md bg-accent/25 px-2 py-1 text-[10px] font-bold text-foreground">{summary.data?.architectureVersion || 'v1'}</span></div>
        {summary.isLoading ? <div className="mt-8 space-y-3"><div className="skeleton-shimmer h-12 rounded-xl" /><div className="skeleton-shimmer h-12 rounded-xl" /></div> : summary.isError ? <div className="mt-8 rounded-xl bg-destructive/5 p-4 text-sm text-muted-foreground"><CircleAlert className="mb-2 size-5 text-destructive" />{labels.snapshotUnavailable}<button type="button" onClick={() => summary.refetch()} className="mt-3 block rounded-lg bg-destructive px-3 py-2 text-xs font-bold text-destructive-foreground" data-testid="button-retry-summary">{labels.retry}</button></div> : <div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted/70 p-4"><div className="text-2xl font-bold">{summary.data?.onlineProviderCount ?? 0}<span className="text-sm text-muted-foreground">/{summary.data?.providerCount ?? 0}</span></div><p className="mt-1 text-xs text-muted-foreground">{labels.online}</p></div><div className="rounded-xl bg-muted/70 p-4"><div className="flex items-center gap-2 text-sm font-bold">{summary.data?.cacheEnabled ? <CheckCircle2 className="size-4 text-primary" /> : <WifiOff className="size-4 text-destructive" />}{summary.data?.cacheEnabled ? labels.cache : labels.cacheOffline}</div><p className="mt-2 text-xs text-muted-foreground">{labels.architecture} {summary.data?.architectureVersion}</p></div></div>}
        {summary.data?.notices && summary.data.notices.length > 0 && <div className="mt-5 border-t border-border pt-4"><p className="mono-font mb-3 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{labels.notices}</p>{summary.data.notices.map((notice) => <p key={notice} className="flex gap-2 text-xs leading-6 text-muted-foreground"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-accent" />{notice}</p>)}</div>}
      </div>
      <div className="rounded-2xl border border-card-border bg-card p-5 sm:p-6">
        <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-accent text-accent-foreground"><Globe2 className="size-5" /></div><div><h2 className="font-bold">{labels.preferences}</h2><p className="text-xs text-muted-foreground">{labels.language} · {labels.appearance}</p></div></div>
        <div className="mt-7 space-y-5"><div><label className="text-xs font-bold text-muted-foreground">{labels.language}</label><div className="mt-2 grid grid-cols-3 gap-2">{(['en', 'fr', 'ar'] as const).map((item) => <button type="button" key={item} onClick={() => setLanguage(item)} className={`h-10 rounded-lg border text-xs font-bold ${language === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-muted/50 text-muted-foreground'}`} data-testid={`button-language-${item}`}>{item === 'en' ? 'English' : item === 'fr' ? 'Français' : 'العربية'}</button>)}</div></div><div><label className="text-xs font-bold text-muted-foreground">{labels.appearance}</label><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => setDark(false)} className={`flex h-10 items-center justify-center gap-2 rounded-lg border text-xs font-bold ${!dark ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-muted/50 text-muted-foreground'}`} data-testid="button-theme-light"><Sun className="size-3.5" />{labels.light}</button><button type="button" onClick={() => setDark(true)} className={`flex h-10 items-center justify-center gap-2 rounded-lg border text-xs font-bold ${dark ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-muted/50 text-muted-foreground'}`} data-testid="button-theme-dark"><Moon className="size-3.5" />{labels.dark}</button></div></div></div>
      </div>
    </section>
    <section className="rounded-2xl border border-card-border bg-card p-5 sm:p-6">
      <div className="flex items-center justify-between gap-3"><div><p className="mono-font text-[10px] font-bold uppercase tracking-[0.18em] text-primary">{labels.providers}</p><h2 className="mt-2 text-xl font-bold">{labels.operations}</h2></div><Gauge className="size-5 text-muted-foreground" /></div>
      <div className="mt-6 divide-y divide-border/70">{providers.isLoading ? [0, 1].map((index) => <div key={index} className="flex items-center justify-between py-4"><div className="skeleton-shimmer h-4 w-32 rounded" /><div className="skeleton-shimmer h-4 w-20 rounded" /></div>) : providers.isError ? <div className="py-8 text-center text-sm text-muted-foreground"><WifiOff className="mx-auto mb-3 size-5" />{labels.providerUnavailable}<button type="button" onClick={() => providers.refetch()} className="mx-auto mt-3 block rounded-lg border border-border px-3 py-2 text-xs font-bold" data-testid="button-retry-providers">{labels.retry}</button></div> : providers.data?.length === 0 ? <div className="py-8 text-center text-sm text-muted-foreground"><Server className="mx-auto mb-3 size-5" />{labels.noProviders}</div> : (providers.data || []).map((provider) => { const online = provider.status === 'ONLINE'; const degraded = provider.status === 'DEGRADED' || provider.status === 'RATE_LIMITED'; return <div key={provider.provider} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between" data-testid={`row-provider-${provider.provider}`}><div className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-full ${online ? 'bg-accent/35 text-primary' : degraded ? 'bg-amber-500/15 text-amber-700 dark:text-amber-300' : 'bg-destructive/10 text-destructive'}`}>{online ? <CheckCircle2 className="size-4" /> : <CircleAlert className="size-4" />}</span><div><p className="text-sm font-bold">{provider.displayName}</p><p className="text-xs text-muted-foreground">{provider.lastError || (provider.enabled ? labels.ready : labels.disabled)}</p></div></div><div className="flex items-center gap-4 ps-12 text-xs sm:ps-0"><span className={`font-bold ${online ? 'text-primary' : degraded ? 'text-amber-700 dark:text-amber-300' : 'text-destructive'}`}>{statusLabels[provider.status as keyof typeof statusLabels] || provider.status}</span>{provider.responseTimeMs !== null && <span className="flex items-center gap-1 text-muted-foreground"><Clock3 className="size-3" /> {provider.responseTimeMs}ms</span>}</div></div>; })}</div>
      {summary.data?.generatedAt && <p className="mt-5 flex items-center gap-2 text-[10px] text-muted-foreground"><Database className="size-3" /> {labels.refreshed} {new Date(summary.data.generatedAt).toLocaleString(language)}</p>}
    </section>
  </div>;
}